package com.real.userserver.user.model;

import java.util.Date;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_auth_id
     *
     * @mbg.generated
     */
    private Integer userAuthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id_type
     *
     * @mbg.generated
     */
    private String idType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_account
     *
     * @mbg.generated
     */
    private String authAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.auth_pass
     *
     * @mbg.generated
     */
    private String authPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_auth_id
     *
     * @return the value of user_auth.user_auth_id
     *
     * @mbg.generated
     */
    public Integer getUserAuthId() {
        return userAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_auth_id
     *
     * @param userAuthId the value for user_auth.user_auth_id
     *
     * @mbg.generated
     */
    public void setUserAuthId(Integer userAuthId) {
        this.userAuthId = userAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.id_type
     *
     * @return the value of user_auth.id_type
     *
     * @mbg.generated
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.id_type
     *
     * @param idType the value for user_auth.id_type
     *
     * @mbg.generated
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_account
     *
     * @return the value of user_auth.auth_account
     *
     * @mbg.generated
     */
    public String getAuthAccount() {
        return authAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_account
     *
     * @param authAccount the value for user_auth.auth_account
     *
     * @mbg.generated
     */
    public void setAuthAccount(String authAccount) {
        this.authAccount = authAccount == null ? null : authAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.auth_pass
     *
     * @return the value of user_auth.auth_pass
     *
     * @mbg.generated
     */
    public String getAuthPass() {
        return authPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.auth_pass
     *
     * @param authPass the value for user_auth.auth_pass
     *
     * @mbg.generated
     */
    public void setAuthPass(String authPass) {
        this.authPass = authPass == null ? null : authPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_id
     *
     * @return the value of user_auth.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_id
     *
     * @param userId the value for user_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.last_login_time
     *
     * @return the value of user_auth.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.last_login_time
     *
     * @param lastLoginTime the value for user_auth.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}