package com.real.userserver.user.dao;

import com.real.userserver.user.model.RoleU;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

/**
 * @author asuis
 */
@Mapper
public interface RoleUMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_u
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_u
     *
     * @mbg.generated
     */
    int insert(RoleU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_u
     *
     * @mbg.generated
     */
    int insertSelective(RoleU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_u
     *
     * @mbg.generated
     */
    RoleU selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_u
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_u
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleU record);
}